version: '3.9'

services:

  frontend.web.passport:
    container_name: "frontend.web.passport"

    build:
      context: ../
      dockerfile: docker/proxy/Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
        - REACT_APP_VERSION=1.0.0-Docker
        - REDIRECT_PROFILE_PAGE=http://localhost:9030/account
    ports:
      - "9020:80"